version: 2.1

jobs:
  frontend-build-and-push:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build Frontend Image
          command: |
            docker build -t gaffar08/todo-frontend ./frontend

      - run:
          name: Push Frontend Image
          command: |
            docker push gaffar08/todo-frontend

workflows:
  version: 2
  build:
    jobs:
      - frontend-build-and-push