version: 2.1

jobs:
  backend-build-and-push:
    machine: true
    steps:
      - checkout

      - run:
          name: Skip if CI Bot Commit
          command: |
            COMMIT_AUTHOR=$(git log -1 --pretty=%an)
            if echo "$COMMIT_AUTHOR" | grep -q "CircleCI Bot"; then
              echo "Commit is from CircleCI Bot — skipping pipeline"
              circleci step halt
            fi

      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install

      - run:
          name: DockerHub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # - run:
      #     name: OWASP Dependency Check Backend
      #     command: |
      #       mkdir -p backend-report
      #       docker run --rm \
      #         -e NVD_API_KEY=${NVD_API_KEY} \
      #         -v $(pwd):/src \
      #         owasp/dependency-check:latest \
      #         --nvdApiKey ${NVD_API_KEY} \
      #         --scan /src/backend \
      #         --format JSON \
      #         --out /src/backend-report || true

      # - store_artifacts:
      #     path: backend-report

      - run:
          name: Build Backend Docker Image
          command: |
            docker build \
            -t gaffar08/todo-backend:$CIRCLE_BUILD_NUM \
            ./backend

      - run:
          name: Trivy Backend Scan
          command: |
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              aquasec/trivy image \
              gaffar08/todo-backend:$CIRCLE_BUILD_NUM

      - run:
          name: Push Backend Docker Image
          command: |
            docker push gaffar08/todo-backend:$CIRCLE_BUILD_NUM

      - run:
          name: Update Backend Manifest in Git
          command: |
            git config user.email "circleci@bot.com"
            git config user.name "CircleCI Bot"
            sed -i "s|gaffar08/todo-backend:.*|gaffar08/todo-backend:$CIRCLE_BUILD_NUM|" \
              k8s/backend/deployment.yaml
            git add k8s/backend/deployment.yaml
            git commit -m "ci: update backend image to $CIRCLE_BUILD_NUM [ci skip]"
            git push https://$GITHUB_TOKEN@github.com/Gaffar08/todo-app.git main

  frontend-build-and-push:
    machine: true
    steps:
      - checkout

      - run:
          name: Skip if CI Bot Commit
          command: |
            COMMIT_AUTHOR=$(git log -1 --pretty=%an)
            if echo "$COMMIT_AUTHOR" | grep -q "CircleCI Bot"; then
              echo "Commit is from CircleCI Bot — skipping pipeline"
              circleci step halt
            fi

      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

      - run:
          name: DockerHub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # # - run:
      #     name: OWASP Dependency Check Frontend
      #     command: |
      #       mkdir -p frontend-report
      #       docker run --rm \
      #         -e NVD_API_KEY=${NVD_API_KEY} \
      #         -v $(pwd):/src \
      #         owasp/dependency-check:latest \
      #         --nvdApiKey ${NVD_API_KEY} \
      #         --scan /src/frontend \
      #         --format JSON \
      #         --out /src/frontend-report || true

      # - store_artifacts:
      #     path: frontend-report

      - run:
          name: Build Frontend Docker Image
          command: |
            docker build \
            -t gaffar08/todo-frontend:$CIRCLE_BUILD_NUM \
            ./frontend

      - run:
          name: Trivy Frontend Scan
          command: |
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              aquasec/trivy image \
              gaffar08/todo-frontend:$CIRCLE_BUILD_NUM

      - run:
          name: Push Frontend Docker Image
          command: |
            docker push gaffar08/todo-frontend:$CIRCLE_BUILD_NUM

      - run:
          name: Update Frontend Manifest in Git
          command: |
            git config user.email "circleci@bot.com"
            git config user.name "CircleCI Bot"
            sed -i "s|gaffar08/todo-frontend:.*|gaffar08/todo-frontend:$CIRCLE_BUILD_NUM|" \
              k8s/frontend/deployment.yaml
            git add k8s/frontend/deployment.yaml
            git commit -m "ci: update frontend image to $CIRCLE_BUILD_NUM [ci skip]"
            git push https://$GITHUB_TOKEN@github.com/Gaffar08/todo-app.git main

workflows:
  version: 2
  build-and-push:
    jobs:
      - backend-build-and-push
      - frontend-build-and-push