version: 2.1

jobs:

  backend-build-and-push:
    machine: true

    steps:
      - checkout

      - run:
          name: DockerHub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Install Java
          command: |
            sudo apt update
            sudo apt install -y default-jre unzip wget

      - run:
          name: OWASP Dependency Check Backend
          command: |
            wget https://github.com/dependency-check/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip

            unzip dependency-check-9.0.9-release.zip

            ./dependency-check/bin/dependency-check.sh \
            --project "todo-backend" \
            --scan backend \
            --format HTML \
            --out backend-report

      - store_artifacts:
          path: backend-report

      - run:
          name: Build Backend Docker Image
          command: |
            docker build -t gaffar08/todo-backend:latest ./backend

      - run:
          name: Trivy Backend Scan
          command: |
            docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image \
            gaffar08/todo-backend:latest

      - run:
          name: Push Backend Docker Image
          command: |
            docker push gaffar08/todo-backend:latest

  frontend-build-and-push:
    machine: true

    steps:
      - checkout

      - run:
          name: DockerHub Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Install Java
          command: |
            sudo apt update
            sudo apt install -y default-jre unzip wget

      - run:
          name: OWASP Dependency Check Frontend
          command: |
            wget https://github.com/dependency-check/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip

            unzip dependency-check-9.0.9-release.zip

            ./dependency-check/bin/dependency-check.sh \
            --project "todo-frontend" \
            --scan frontend \
            --format HTML \
            --out frontend-report

      - store_artifacts:
          path: frontend-report

      - run:
          name: Build Frontend Docker Image
          command: |
            docker build -t gaffar08/todo-frontend:latest ./frontend

      - run:
          name: Trivy Frontend Scan
          command: |
            docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image \
            gaffar08/todo-frontend:latest

      - run:
          name: Push Frontend Docker Image
          command: |
            docker push gaffar08/todo-frontend:latest

workflows:
  version: 2

  build-and-push:
    jobs:
      - backend-build-and-push
      - frontend-build-and-push